### ISSUE TITLE
Can we merge this directly into this repo?

### ISSUE THREAD

**Issue by ericduran** [drupalcampnyc/dcnyc10#7]
https://github.com/zroger/cod_api/pull/2

This is preventing the launch of the Android app.

**Comment by FatherShawn** [comment]
If we can, I don't know how.  This is a pull request to roger's fork, which he can accept and then issue a pull request back to this repo.

**Comment by ericduran** [comment]
@fatherShawn, we could just merge the code manually -> https://github.com/ericduran/cod_api/commit/e9ae1ed32e89f1b36c37dc659aa972b905fcc652
